services:
  # PHP Laravel Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: attendance-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - attendance-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: attendance-webserver
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - attendance-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: attendance-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: attendance_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: dbpassword
      MYSQL_USER: attendance_user
    ports:
      - "3315:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - attendance-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: attendance-redis
    restart: unless-stopped
    ports:
      - "6385:6379"
    networks:
      - attendance-network

volumes:
  dbdata:
    driver: local

networks:
  attendance-network:
    driver: bridge